pipeline:
    name: test
    identifier: test
    projectIdentifier: goHelloWorld
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: goHelloWorld
                build: <+input>
    stages:
        - stage:
              name: test
              identifier: test
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: org.GKEdefault
                          namespace: default
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: org.Docker_Hub
                                    image: buster
                                    shell: Sh
                                    command: echo test
        - stage:
              name: testdeploy
              identifier: testdeploy
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: goHelloWorld
                      serviceDefinition:
                          spec:
                              variables: []
                          type: Kubernetes
                  infrastructure:
                      environmentRef: Test
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: org.GKEdefault
                              namespace: default
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
