pipeline:
    name: CD Pipeline
    identifier: CD_Pipeline
    allowStageExecutions: false
    projectIdentifier: goHelloWorld
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Deploy to prod
              identifier: Deploy_to_prod
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: goHelloWorld
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: Deployment
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: goHelloWorld
                                                    gitFetchType: Branch
                                                    paths:
                                                        - deployment.yaml
                                                    branch: main
                                            skipResourceVersioning: false
                                  - manifest:
                                        identifier: ValuesProd
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: goHelloWorld
                                                    gitFetchType: Branch
                                                    paths:
                                                        - valuesProd.yaml
                                                    branch: main
                              artifacts:
                                  primary:
                                      spec:
                                          connectorRef: org.Docker_Hub
                                          imagePath: rmailaender/gohelloworldserver
                                          tag: <+input>
                                      type: DockerRegistry
                  infrastructure:
                      environmentRef: Test
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: org.GKEdefault
                              namespace: goserver-prod
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - stepGroup:
                                name: Canary Deployment
                                identifier: canaryDepoyment
                                steps:
                                    - step:
                                          name: Canary Deployment
                                          identifier: canaryDeployment
                                          type: K8sCanaryDeploy
                                          timeout: 10m
                                          spec:
                                              instanceSelection:
                                                  type: Count
                                                  spec:
                                                      count: 1
                                              skipDryRun: false
                                    - step:
                                          name: Canary Delete
                                          identifier: canaryDelete
                                          type: K8sCanaryDelete
                                          timeout: 10m
                                          spec: {}
                                rollbackSteps:
                                    - step:
                                          name: Canary Delete
                                          identifier: rollbackCanaryDelete
                                          type: K8sCanaryDelete
                                          timeout: 10m
                                          spec: {}
                          - stepGroup:
                                name: Primary Deployment
                                identifier: primaryDepoyment
                                steps:
                                    - step:
                                          name: Rolling Deployment
                                          identifier: rollingDeployment
                                          type: K8sRollingDeploy
                                          timeout: 10m
                                          spec:
                                              skipDryRun: false
                                          failureStrategies: []
                                rollbackSteps:
                                    - step:
                                          name: Rolling Rollback
                                          identifier: rollingRollback
                                          type: K8sRollingRollback
                                          timeout: 10m
                                          spec: {}
                      rollbackSteps: []
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
              variables: []
        - stage:
              name: Dashboards
              identifier: Dashboards
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      useFromStage:
                          stage: Deploy_to_prod
                  infrastructure:
                      environmentRef: Test
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: org.GKEdefault
                              namespace: default
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: TerraformPlan
                                name: Plan Splunk Dashboard
                                identifier: Plan_Splunk_Dashboard
                                spec:
                                    configuration:
                                        command: Apply
                                        configFiles:
                                            store:
                                                type: Github
                                                spec:
                                                    gitFetchType: Branch
                                                    connectorRef: goHelloWorld
                                                    branch: main
                                                    folderPath: dashboards/splunk
                                        secretManagerRef: org.harnessSecretManager
                                    provisionerIdentifier: f6d4fe7634a3
                                timeout: 10m
                                failureStrategies: []
                          - step:
                                type: TerraformApply
                                name: Apply Splunk Dashboard
                                identifier: Apply_Splunk_Dashboard
                                spec:
                                    provisionerIdentifier: f6d4fe7634a3
                                    configuration:
                                        type: InheritFromPlan
                                timeout: 10m
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
